project:
  type: website
  output-dir: _site

website:
  title: "Herramientas digitales para lingüística"
  site-url: https://hdl.juanpaulo.xyz/course
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



