project:
  type: website
  output-dir: _site

website:
  title: "Herramientas digitales para lingüística"
  site-url: https://hdl.juanpaulo.xyz/course
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: about.qmd
        text: Sobre este curso
      - href: tutorials/index.qmd
        text: Tutoriales

lang: es

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-title: "En este capítulo"
    code-fold: false
    code-tools: true
    filters:
      - pyodide


